config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'welcome#index'
  resources :users, only: %i[index show new] do
    resources :categories, only: %i[new create show index destroy]
    resources :payments, only: %i[new create index show destroy]
  end
  get '/welcome', to: 'welcome#index', as: 'welcome_index'
  get 'categories', to: 'categories#index', as: 'categories_index'
  get 'payments', to: 'payments#index', as: 'payments_index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :payment_categories, dependent: :destroy
  has_many :payments, through: :payment_categories, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  has_many :payment_categories, dependent: :destroy
  has_many :categories, through: :payment_categories, dependent: :destroy

  # Valudation
  validates :name, presence: true, length: { minimum: 2 }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/payment_category.rb
class PaymentCategory < ApplicationRecord
  belongs_to :category
  belongs_to :payment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Validations
  validates :name, presence: true, length: { in: 2..40 }

  # Associations
  has_many :payments, dependent: :destroy
  has_many :categories, class_name: 'Category', foreign_key: 'author_id', dependent: :destroy
  has_many :payment_categories, through: :payments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Set up user authentication
  before_action :authenticate_user!, unless: :welcome_index_url
  # Add addtional parameters
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Customize redirect hooks
  def after_sign_in_path_for(_resource)
    user_categories_url(current_user)
  end
  # Permit addtional parameters (@lazy)

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up, keys: %i[name email password confirm_password]
    )
    devise_parameter_sanitizer.permit(
      :sign_in, keys: %i[email password]
    )
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @author = current_user
    @categories = Category.all
    @category_sums = {}
    @categories.each do |category|
      @category_sums[category.id] = category.payments.sum(:amount)
    end
  end

  def show; end

  def new
    @category = Category.new
  end

  def create
    @author = current_user
    @category = @author.categories.build(author_id: current_user.id, **category_params)
    if @category.save
      flash[:success] = 'Category successfully added.'
      redirect_to user_categories_path(@author)
    else
      flash[:error] = 'error while adding Category.'
      render :new
    end
  end

  def destroy; end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/payments_categories_controller.rb
class PaymentsCategoriesController < ApplicationController
  def index; end

  def show; end

  def new; end

  def create; end

  def destroy; end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @payments = Payment.all
    @categories = Category.all
  end

  def show
    @category_id = params[:id]
    @category = Category.find(@category_id)
    @category_name = @category.name
    payment_categories = PaymentCategory.where(category_id: @category_id)
    @payments = Payment.where(id: payment_categories.pluck(:payment_id)).order(created_at: :desc)
    @sum = @payments.sum(:amount)
  end

  def new
    @payment = Payment.new
    @categories = Category.all
  end

  def create
    @payment = Payment.new(author_id: current_user.id, **payment_params)
    category_ids = params[:payment][:category_ids].reject(&:empty?)

    if @payment.save
      category_ids.each do |category_id|
        PaymentCategory.create(payment: @payment, category_id:)
      end
      my_category = category_ids.first
      flash[:success] = 'Payment successfully added.'
      redirect_to user_payment_url(author_id: current_user.id, id: my_category)
    else
      flash[:error] = 'Error while adding payment.'
      render :new
    end
  end

  def destroy
    return unless @payment.destroy

    redirect_to user_payments_url
  end

  private

  def payment_params
    params.require(:payment).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show; end

  def new; end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/payments_categories_helper.rb
module PaymentsCategoriesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/index.html.erb
<header class="header-category">
  <nav class="nav-list">
    <i class="fas fa-bars"></i>
    <h1 class="h1-categories">Categories</h1>
    <i class="fas fa-search"></i>
  </nav>
</header>

<section class="category-container">
  <% if @categories.empty? %>
    <p>There are no categories for the budget</p>
  <% else %>
    <% @categories.each do |category| %>
      <article class="article-list">
        <%= link_to user_payment_path(current_user.id, category.id) do %>
          <div class="icon-name-sum">
            <div class="icon"><%=image_tag(category.icon, :alt => "category icon.", :class => "category-icon") %></div>
            <div class="name"><%= category.name %></div>
            <div class="sum"><span class="">$<%= @category_sums[category.id] %></span></div>
          </div>
        <% end %>
      </article>
    <% end %>
  <% end %>

  <div class="category-button">
    <%= link_to "Add a new Category", new_user_category_path(current_user), class: "insert-category" %>
  </div>
</section>

app/views/categories/new.html.erb
<div class="category-form">
<header class="header-category">
<nav class="nav-list">
<%= link_to user_categories_path(current_user) do %>
  <i class="fas fa-less-than"></i>
  <% end %>
<h1> New Category</h1>
<i class="fas fa-search"></i>
</nav>
</header>

<div class="category-name-icon">
<%= form_with(model: @category, url: user_categories_path) do |form| %>
    <div class="form">
   
  <div class="input-name-icon">
    <%= form.text_field :name, class: "name-field", placeholder: "Name" %>
    <%= form.text_field :icon, class: "icon-field", placeholder: "Icon"  %>
  </div>
  <div class="category-button">
    <p><%= form.submit "Save", class: "save-category" %></p>
  </div>
  </div>
<% end %>
<div>
</div>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/payments/create.html.erb
<h1>Payments#create</h1>
<p>Find me in app/views/payments/create.html.erb</p>

app/views/payments/destroy.html.erb
<h1>Payments#destroy</h1>
<p>Find me in app/views/payments/destroy.html.erb</p>

app/views/payments/index.html.erb
<h1>Payments#index</h1>
<p>Find me in app/views/payments/index.html.erb</p>

app/views/payments/new.html.erb
<header class="header-pay">
<nav class="nav-list">
<%= link_to user_categories_path(current_user) do %>
  <i class="fas fa-less-than"></i>
  <% end %>
<h1>New Payment</h1>
<i class="fas fa-search"></i>
</nav>
</header>

<div class="input-name-amount">
<%= form_for @payment, url: user_payments_path, method: :post do |f| %>
    <div class="label-payment">
      <%= f.text_field :name, class: "name-field", placeholder: "Name", required: true %>
    <%= f.number_field :amount, class: "amount-field", placeholder: "Amount", required: true %>
  </div>
  
  <div class="categories-li">
  <div class="category-checkbox">
  <%= f.label :category_ids, "Categories", class: "category-label" %>
  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
    <div class="form-check">
      <%= cb.check_box(class: "form-check-input") %>
      <%= cb.label(class: "form-check-label") %>
    </div>
  <% end %>
</div>
</div>
</div>
    <div class="save-btn">
      <%= f.submit "Save", class: "submit-save-btn" %>
    </div>
  <% end %>
 
 

app/views/payments/show.html.erb
<header class="header-pay">
<nav class="nav-list">
<%= link_to user_categories_path(current_user) do %>
<i class="fas fa-less-than"></i>
<% end %>
<h1>Payments</h1>
<i class="fas fa-search"></i>
</nav>
<div class="recent-ancient">
<p class="p1">Most recent</p>
<p class="p2">Most Ancient</p>
</div>
<span class="dot another-class">.</span>
</header>

<section class="payments-section">
<div class="up">
<p><%= @category_name %></p>
<h3>$<%= @sum %></h3>
</div>
<% if @payments.empty? %>
<p>There are no payments for this category</p>
<% else %>
<% @payments.each do |payment| %>
    <article class="payment-article">
    <div class="payment-div">
    <%=image_tag(@category.icon, :alt => "category icon.", :class => "category-payment-icon") %>
<p class="payment-name"><%= payment.name %></p>
<h4>$<%= payment.amount %></h4>
</div>
<div class="date">
<p class="date-of-pay"><%= payment.created_at.strftime('%Y-%m-%d') %></p>
</div>
    </article>
    <% end %>
    <% end %>
    <div class="transaction-btn">
    <%= button_to "Add a payment" , new_user_payment_path, method: :get, class: "add-payment" %>
    </div>
</section>

app/views/payments_categories/create.html.erb
<h1>PaymentsCategories#create</h1>
<p>Find me in app/views/payments_categories/create.html.erb</p>

app/views/payments_categories/destroy.html.erb
<h1>PaymentsCategories#destroy</h1>
<p>Find me in app/views/payments_categories/destroy.html.erb</p>

app/views/payments_categories/index.html.erb
<h1>PaymentsCategories#index</h1>
<p>Find me in app/views/payments_categories/index.html.erb</p>

app/views/payments_categories/new.html.erb
<h1>PaymentsCategories#new</h1>
<p>Find me in app/views/payments_categories/new.html.erb</p>

app/views/payments_categories/show.html.erb
<h1>PaymentsCategories#show</h1>
<p>Find me in app/views/payments_categories/show.html.erb</p>

app/views/users/categories/create.html.erb
<h1>Users::Categories#create</h1>
<p>Find me in app/views/users/categories/create.html.erb</p>

app/views/users/categories/destroy.html.erb
<h1>Users::Categories#destroy</h1>
<p>Find me in app/views/users/categories/destroy.html.erb</p>

app/views/users/categories/index.html.erb
<h1>Users::Categories#index</h1>
<p>Find me in app/views/users/categories/index.html.erb</p>

app/views/users/categories/new.html.erb
<h1>Users::Categories#new</h1>
<p>Find me in app/views/users/categories/new.html.erb</p>

app/views/users/categories/show.html.erb
<h1>Users::Categories#show</h1>
<p>Find me in app/views/users/categories/show.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/welcome/index.html.erb
<div class="welcome-container">
  <h1 class="welcome-h1">Welcome to budget app!</h1>
  <div class="button-control">
    <button class="log-btn">
      <%= link_to "LOG IN", new_user_session_path, class: 'submit-btn' %>
    </button>
    <button class="sign-btn">
      <%= link_to "SIGN UP", new_user_registration_path, class: 'submit-btn' %>
    </button>
  </div>
</div>